### ISSUE TITLE
Project indentation code style?

### ISSUE THREAD

**Issue by pfalcon** [alexshpilkin/dvrip#5]
PEP8 clearly says [Spaces are the preferred indentation method.](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces). And large majority of Python project follow. But dvrip uses tabs. That's in sharp contrast to having a testsuite, using type annotations, etc. Is there a reason for that?

**Comment by alexshpilkin** [comment]
The simple answer is that I like it that way. I prefer my code (in whatever language) indented with tabs and aligned with spaces (see https://www.emacswiki.org/emacs/SmartTabs). If I had an objective reason to switch over—_e.g._ a contributor that couldn’t configure their editor that way—I would do so, but I don’t.

**Comment by pfalcon** [comment]
Sounds good, thanks for reply.
